logo: A<span>tom</span> # add logo name
title: Story of Atom
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://atomthink.com" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Story of Atom # add banner title
banner-desc: 일단 떠나자 # add banner description

# Author settings
author-pic: me.jpg # your photo
author-name: atom # your name
about-author: 사진으로 낙서하는 개발자 # about author
email: ojs0106@gmail.com # your email
phone: (82)10-2040-8227 # your pnone number
website: https://atomthink.com/blog # you website

# Social link
# google_url:    # add url link
# twitter_url:   # add url link
# instagram_url: # add url link
# pinterest_url: # add url link
# dribbble_url:  # add url link
# facebook_url:  # add url link

# Disqus
discus_identifier: https://atomwow # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: https://gmail.us3.list-manage.com/subscribe/post?u=2ec260a4e064ca146f217f572&amp;id=e3a413bbd2 # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics: UA-146505718-1

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
